# -*- coding: utf-8 -*-
"""Marketing Analytics Paper 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QEqYbiaeWBO5PxtC84H06TBC_i7WB_cQ
"""

#import
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.mixture import GaussianMixture

file_path = "Credit Card Customer Data.csv"

df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "aryashah2k/credit-card-customer-data",
  file_path,
)

print("First 5 records:", df.head())

cols_to_drop = ['Sl_No', 'Customer Key']
X = df.drop(columns=[col for col in cols_to_drop if col in df.columns])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

algo_scores = {}

plt.figure(figsize=(20, 10))
sns.set(style="whitegrid")

# 1. K-Means clustering
best_score_kmeans = -1
best_k_kmeans = -1
best_labels_kmeans = []

for k in range(2, 7):
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    if score > best_score_kmeans:
        best_score_kmeans = score
        best_k_kmeans = k
        best_labels_kmeans = labels

algo_scores[f"KMeans (k={best_k_kmeans})"] = best_score_kmeans

plt.subplot(2, 2, 1)
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=best_labels_kmeans, palette="bright", legend='full')
plt.title(f"KMeans (Best k={best_k_kmeans}, Score={best_score_kmeans:.3f})")

# 2. Agglomerative Clustering
best_score_agg = -1
best_k_agg = -1
best_labels_agg = []

for k in range(2, 7):
    agg = AgglomerativeClustering(n_clusters=k)
    labels = agg.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    if score > best_score_agg:
        best_score_agg = score
        best_k_agg = k
        best_labels_agg = labels

algo_scores[f"Agglomerative (k={best_k_agg})"] = best_score_agg

plt.subplot(2, 2, 2)
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=best_labels_agg, palette="bright", legend='full')
plt.title(f"Agglomerative (Best k={best_k_agg}, Score={best_score_agg:.3f})")

# 3. DBSCAN
best_score_db = -1
best_eps_db = -1
best_labels_db = []
eps_range = [0.5, 0.8, 1.0, 1.2, 1.5, 2.0]

for eps in eps_range:
    db = DBSCAN(eps=eps, min_samples=5)
    labels = db.fit_predict(X_scaled)

    if len(set(labels)) > 1:
        score = silhouette_score(X_scaled, labels)
        if score > best_score_db:
            best_score_db = score
            best_eps_db = eps
            best_labels_db = labels

if best_score_db != -1:
    algo_scores[f"DBSCAN (eps={best_eps_db})"] = best_score_db
    plt.subplot(2, 2, 3)
    sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=best_labels_db, palette="bright", legend='full')
    plt.title(f"DBSCAN (Best eps={best_eps_db}, Score={best_score_db:.3f})")
else:
    algo_scores["DBSCAN"] = -1
    plt.subplot(2, 2, 3)
    plt.text(0.5, 0.5, "DBSCAN failed to find distinct clusters", ha='center')
    plt.title("DBSCAN (Failed)")

# 4. Gaussian Mixture
best_score_gaussian = -1
best_n_gaussian = -1
best_labels_gaussian = []

for n in range(2, 7):
    gaussian = GaussianMixture(n_components=n, random_state=42)
    labels = gaussian.fit_predict(X_scaled)
    score = silhouette_score(X_scaled, labels)
    if score > best_score_gaussian:
        best_score_gaussian = score
        best_n_gaussian = n
        best_labels_gaussian = labels

algo_scores[f"Gaussian (n={best_n_gaussian})"] = best_score_gaussian

plt.subplot(2, 2, 4)
sns.scatterplot(x=X_pca[:, 0], y=X_pca[:, 1], hue=best_labels_gaussian, palette="bright", legend='full')
plt.title(f"Gaussian Mixture (Best n={best_n_gaussian}, Score={best_score_gaussian:.3f})")

plt.tight_layout()
plt.show()

# Algorithm with the highest silhouette

print("Clustering Results Summary")
for algo, score in algo_scores.items():
    print(f"{algo}: {score:.4f}")

best_algo_name = max(algo_scores, key=algo_scores.get)
best_algo_score = algo_scores[best_algo_name]

print("\n" + "="*50)
print(f"Winner: {best_algo_name}")
print(f"{best_algo_score:.4f}")
print("="*50)